ALTER TABLE IF EXISTS experts
ADD COLUMN IF NOT EXISTS total_earned BIGINT NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS bookings
ADD COLUMN IF NOT EXISTS user_reminder INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS expert_reminder INTEGER NOT NULL DEFAULT 0;
