ALTER TABLE IF EXISTS organisations 
DROP COLUMN IF EXISTS purpose,
DROP COLUMN IF EXISTS org_email,
DROP COLUMN IF EXISTS phone,
DROP COLUMN IF EXISTS website,
DROP COLUMN IF EXISTS org_address,
DROP COLUMN IF EXISTS Org_location,
DROP COLUMN IF EXISTS founded_year,
DROP COLUMN IF EXISTS category;

ALTER TABLE IF EXISTS branches
DROP COLUMN IF EXISTS phone,
DROP COLUMN IF EXISTS branch_location;