ALTER TABLE IF EXISTS organisations 
ADD COLUMN IF NOT EXISTS purpose TEXT, 
ADD COLUMN IF NOT EXISTS org_email TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS website TEXT,
ADD COLUMN IF NOT EXISTS org_address TEXT,
ADD COLUMN IF NOT EXISTS Org_location TEXT,
ADD COLUMN IF NOT EXISTS founded_year INTEGER,
ADD COLUMN IF NOT EXISTS category TEXT;


ALTER TABLE IF EXISTS branches
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS branch_location TEXT;

  