
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultout-redis
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultout-redis
  template:
    metadata:
      labels:
        app: consultout-redis
    spec:
      containers:
      - name: redis
        image: redis:7
        ports:
        - containerPort: 6379
        envFrom:
        - secretRef:
            name: consultout-backend-secret

--- 
# PostgreSQL Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consultout-db
  namespace: argocd
spec:
  serviceName: "consultout-db"
  replicas: 1
  selector:
    matchLabels:
      app: consultout-db
  template:
    metadata:
      labels:
        app: consultout-db
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: consultout-backend-secret
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi  



