---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    password: AgBpLFkwHdhrSk6TRnYiCquHwWBpaU3DTovVQ/DkHUmoXBOCUM/yoF29zuTaBvUBadI91DCcYGdLPsDmrB7aDnv+1uXgM45wehEJhKgctYEcLSlGcLxrmdq0i0ZU+IGj5YAjV5ABHkLRVsLb/gKMbtxWb4N28RXLLfbq9cU7fef0+LJ0RNFdP2mk9QSZQZwg2d+iHUEr+zvQkj8X1hL95Ugd6Fb2m9+quK3mq10s1j2xPP4ah/gre7YOLLjMUuGwkLxL1eGVBUIyfinXhJKKD0GeZoj42Ll+qJFL8X5+wz5l4jbMwJzli+RmkMZeXoCR7uBOx54LKFSNaePgkX5/ADD5mZvR8HaQdVYiarEOAJkgo4RgUFNUFEC0YYkf6GRv7dpLXCVX1lmgYR8hYZxCSVT3KVRfulxNsuqR9C/X8mJ/xHFgHcCJGhB4pKKjsnicey5LD3uk5wMxRMCFuGfIedh5cU3zMMpB5DhQB0YMrcOYqgu9nx4Os9QWLLMVW3bzhkYW0LuZ/lLk98lZdxMbVX6eL44/Z/kysxHfbjCUwI7GPUxOMOQrI8hRsAeAhh1ErKhwXJnKWAjUHetow8b+Q8KT48sA5+1XzigB234iNzu74Sl5768TnToXijbDqObNL0AwFcUQDTYEfYVAHhjlHBxVFuvqEXJumLr9YJOk615vQxRHL9+PzY3B6LWat7o7eymk24hY1qwWNtOd3eU=
    username: AgAX+lpXW35a6IM6/hE+du7OqHg9N2VijL1sA1Wpr0M+YrWQ2YwP5vRqQOFker3I/ogjKNG8RKM9GnI0rMLs6lL6q0FXGTFN4AkfySlb/b4pDrDRPd5zdx9rTPH35uxG2qnbRaid1Ueq+4OzZVBiA1uU16SEwM8aRSxXDZxbgbanAaScJkxwX/n/7l0Y++mVl6x0z5FJXu5ihHUI8MD1EVHaz2MCKHZA73v/QB1APnBUyD8ixR6dHYQs+jIyJFkAYDj+4oKxQFasl6j0+PVBi07QACvx0Goj9Y58I2IRBE1bmUIj9tjnj6nnCJMyk61dn+dKYhB+wlB5NFcEYqZW66LnihopGlIkZlcdiWGxNwGdD9jSnCmy33Z0qJxljRKgNtjGpTLXgngSu0Df17qKw3+jywhmuq00W9GXOJKruaZa9RL0x8FD5IkEJOWoQ8i9TbuYUOj3iByR/xM23/3pHAAMXQq9snskjS6Omx8vXagg28+4AFcSiCYeKe4nfUTJKlrdZQdIKFLcQeuHlojb/J+hb6C1X6d5dx2S1+0o3Ofyd8Oy1Ybyx8zAUTuUdvmEWxP1FqxSP6ySeQhJSe04hMgquG+Ro0C80jK6DkMHeH+qOUoeaOxxXuYmbvhRe/WM9a3YM+tMUyhHzB4Dl4XSR+5vQx9r0I469H9SP7se7Ft9RNnJC40BVaUkEVhpfO62iPr/JgaM2A==
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: default
