# PostgreSQL Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consultout-db
spec:
  serviceName: "consultout-db"
  replicas: 1
  selector:
    matchLabels:
      app: consultout-db
  template:
    metadata:
      labels:
        app: consultout-db
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: consultout-backend-config
        - secretRef:
            name: consultout-backend-secret
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 4Gi  
